### ISSUE TITLE
jdbc: NPE when trying to execute update

### ISSUE THREAD

**Issue by ztarvos** [tarantool/tarantool-java#39] opened 2018-09-05 15:05 UTC
Driver throws null pointer exception when trying to execute update (either DML or DDL).

`Statement stmt = conn.createStatement();`
`int count = stmt.executeUpdate("CREATE TABLE test(id INT PRIMARY KEY, val VARCHAR(20))");`

`Exception in thread "main" java.lang.NullPointerException
        at org.tarantool.JDBCBridge.update(JDBCBridge.java:38)
        at org.tarantool.jdbc.SQLStatement.executeUpdate(SQLStatement.java:35)
        at TestJdbcUpdate.main(TestJdbcUpdate.java:18)`

Probably the constants related to IPROTO in the driver are somewhat obsolete.

**Comment by Khatskevich** [comment] 2018-09-05 23:44
The problem is simpler.
It is fixed in brunch https://github.com/tarantool/tarantool-java/tree/kh/fix_dml

**Comment by ztarvos** [comment] 2018-09-06 14:28
Hi!
Actually, I do not see how these changes fix the issue. Probably a test would help. 
My own test finally worked when I changed the two constants in Key.java to be in sync with the fresh tarantool 2.0 branch, namely SQL_INFO(0x42) and SQL_ROW_COUNT(0). It even did return correct row count back.

**Comment by Khatskevich** [comment] 2018-09-06 14:43
Great! Patches are welcome)

P.S. I did not investigate the issue deeply. My patch just let me run my own tests.

**Comment by ztarvos** [comment] 2018-09-06 15:05
Sure, I will prepare a patch. 
Thanks!

**Comment by Totktonada** [comment] 2018-09-16 19:08
@ztarvos Any updates? I see you created the patch. Are you going to open the pull request?

It seems the constants was changed on tarantool side? So, we'll break compatibility with older version if will update them here. What version of tarantool changes it?

**Comment by ztarvos** [comment] 2018-09-17 08:01
Hi!
> @ztarvos Any updates? I see you created the patch. Are you going to open the pull request?
I was hoping to see the test infrastructure merged to the jdbc branch first (PR#50) so I can base my changes on it. My fix contains integration tests which require a tarantool instance running. It will not work without it.

> It seems the constants was changed on tarantool side? So, we'll break compatibility with older version if will update them here. What version of tarantool changes it?
These constants are related to SQL and only present on the connector-1.8jdbc branch of tarantool-java, so I guess nothing is broken. For tarantool itself, I think they appeared in 2.0.

**Comment by Totktonada** [comment] 2018-09-17 10:15
Merged initial test infrastructure with #50.

**Comment by ztarvos** [comment] 2018-09-17 11:32
@Totktonada Thanks! I rebased my fix and am ready to submit it.
@kyukhin Should I create a PR or send a patch via mail?

**Comment by Totktonada** [comment] 2018-09-17 23:13
@ztarvos Feel free to use PRs or the mailing list as you wish. I don't think we should enforce community to follow tarantool engineers' policy. Please, let me in To or CC when a review from me is needed.

To be honest I think that PRs are better for small projects (at least), because allows to catch all related discussions within the one place and don't fragment it across issues and a mailing list. GitHub works great with interlinking anything with anything related :)

**Comment by kyukhin** [comment] 2018-09-20 09:55
Fixed by 8aad0073533fb71b09a2bbf02765e6ce2e1edb01

**Closed by kyukhin** 2018-09-20 09:55 UTC
Labels: bug
